### ISSUE TITLE
Inconsistent use of file endings

### ISSUE THREAD

**Issue by jorabra** [prisma/prisma-content-feedback#18]
**Article Title (if relevant)**
Datamodel & Migrations: https://www.prisma.io/docs/data-model-and-migrations/
But also relevant for every other article which refers to specific files.

**Describe the content issue**
The documentation refers to prisma.{yml,graphql}, .graphqlcofig{,.yml}, schema.{yml,graphql} and there’s probably more examples. Pretty much inconsistent throughout the documentation.

**Describe the solution you'd like to see**
First of all I'd like to see a consistent use of filenames and file endings. When just reading through the documentation this can get very confusing. I'd also like to se a tree structure overview of all the files used throughout the documentation with a short description as a quick reference.

**Comment by nikolasburk** [comment]
Hey @jorabra, thanks so much for opening this issue! I fully agree that the amount of .graphql and .yml files can be confusing and we're constantly working on improving the tooling and documentation for that.

I just went through the docs and fixed the instances of incosistent naming (which mostly were datamodel files that were still suffixed with `.graphql` instead of `.prisma` or `.graphqlconfig` files that weren't suffixed with `.yml`). Please let me know if you come across other consistencies 🙏
