### ISSUE TITLE
Prisma 1.26.1 uses PostgreSQL 11, docker-compose.yml example still references PosgreSQL 10 image

### ISSUE THREAD

**Issue by schrepfler** [prisma/prisma-content-feedback#60]
**Article Title (if relevant)**
https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/

**Describe the content issue**
When opening "Add Prisma and database Docker images
" sections (https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/#add-prisma-and-database-docker-images)
and selecting PostgreSQL, the reference version of PostgreSQL docker image used is `10.5`, this is not compatible with the schema generated by Prisma 1.26.1

**Describe the solution you'd like to see**
How can this issue be resolved?
Update `docker-compose.yml` to reference postgresql:11

**Additional context**

**Comment by nikolasburk** [comment]
Hey @schrepfler, thanks a lot for opening this issue! 🙌  The latest Prisma versions (1.26 and 1.27) _should_ be running fine with Postgres 10.x. If you're experiencing any issues with the deployment, please [create a bug report in the main GitHub repo](https://github.com/prisma/prisma/issues/new?template=bug_report.md).

I have however adjusted the version in all Postgres images to 10.3 since that's the version our test suite is running on.
